services:
  broker:
    # Define a imagem do Docker a ser usada para o Kafka
    image: apache/kafka:latest
    container_name: broker  # Define o nome do container como 'broker'
    
    ports:
      - 9092:9092  # Mapeia a porta 9092 do container (Kafka) para a porta 9092 do host
      # Isso permite que o Kafka seja acessado na porta 9092 do host

    environment:
      # Configurações do Kafka via variáveis de ambiente
      KAFKA_NODE_ID: 1  # Define o ID do nó do broker, usado para identificar o broker no cluster Kafka

      # Define os papéis do broker, neste caso, este broker é um 'broker' e um 'controller'
      KAFKA_PROCESS_ROLES: broker,controller

      # Define os listeners do Kafka, ou seja, as interfaces nas quais o Kafka escuta as conexões
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      # PLAINTEXT://0.0.0.0:9092 permite conexões no protocolo PLAINTEXT na porta 9092
      # CONTROLLER://0.0.0.0:9093 permite conexões no protocolo CONTROLLER na porta 9093

      # Define como o Kafka anuncia seus listeners para os clientes
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # Isso faz com que o Kafka anuncie o listener 'PLAINTEXT' na porta 9092 para os consumidores

      # Define quais listeners são usados para o protocolo de controle
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      # Especifica que o protocolo de controle usa o listener 'CONTROLLER'

      # Mapeia os protocolos de segurança dos listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # Define que o protocolo PLAINTEXT será usado tanto para 'CONTROLLER' quanto para 'PLAINTEXT'

      # Define os membros do quorum para o controle de metadados (necessário para o modo de controle de Kafka)
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      # O broker com ID 1 será o único membro do quorum, ouvindo na porta 9093

      # Define o fator de replicação do tópico de offsets (controla as réplicas de offsets de consumidores)
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # Apenas uma réplica será mantida para os offsets

      # Define o fator de replicação para o log de estado das transações
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      # Apenas uma réplica será mantida para o log de estado das transações

      # Define o número mínimo de réplicas que devem estar ativas no log de transações
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # Apenas uma réplica deve estar ativa no log de transações

      # Define o tempo de espera para o reequilíbrio inicial do grupo de consumidores
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # Configura o atraso para 0 milissegundos, ou seja, sem atraso no reequilíbrio inicial

      # Define o número de partições para os tópicos Kafka criados por padrão
      KAFKA_NUM_PARTITIONS: 3
      # O número de partições padrão para novos tópicos será 3
