services:
  broker:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - 9092:9092
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092       # <-- IMPORTANTE: usar o nome do serviço aqui
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 1


  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      - 'MONGO_INITDB_DATABASE=kafka_db'        # Nome do banco de dados
      - 'MONGO_INITDB_ROOT_USERNAME=root'         # Usuário root
      - 'MONGO_INITDB_ROOT_PASSWORD=rootpassword' # Senha do root
    volumes:
      - ./data/db:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root          # Usuário root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword  # Senha do root
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/kafka_db?authSource=admin
      ME_CONFIG_BASICAUTH: false

  app:
    build: .
    container_name: spring-app
    ports:
      - "8080:8080"
    command: ["./wait-for-it.sh", "mongodb:27017", "--", "java", "-jar", "/app.jar"]
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
      SPRING_DATA_MONGODB_URI: mongodb://root:rootpassword@mongodb:27017/kafka_db?authSource=admin
    depends_on:
      - broker
      - mongo